import { useState } from "react";
import UserDashboardLayout from "@/components/UserDashboardLayout";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { Download, Landmark, PiggyBank, Repeat2, TrendingUp } from "lucide-react";

export default function WealthHub() { return <UserDashboardLayout><WealthContent /></UserDashboardLayout>; }
function WealthContent() {
  const utils = trpc.useUtils(); const [tab, setTab] = useState<"staking" | "vaults" | "analytics" | "recurring">("staking");
  const [asset, setAsset] = useState("USDT"); const [amount, setAmount] = useState("100"); const [vaultName, setVaultName] = useState("Emergency Fund");
  const [paymentMethodToken, setPaymentMethodToken] = useState("");
  const stakes = trpc.advanced.staking.list.useQuery(); const vaults = trpc.advanced.vaults.list.useQuery(); const schedules = trpc.advanced.vaults.schedules.useQuery(); const analytics = trpc.advanced.analytics.portfolio.useQuery(); const loyalty = trpc.advanced.loyalty.status.useQuery();
  const refresh = () => Promise.all([utils.advanced.staking.list.invalidate(), utils.advanced.vaults.list.invalidate(), utils.advanced.vaults.schedules.invalidate(), utils.wallet.list.invalidate()]);
  const stake = trpc.advanced.staking.create.useMutation({ onSuccess: async () => { await refresh(); toast.success("Stake activated"); }, onError: (e) => toast.error(e.message) });
  const unstake = trpc.advanced.staking.withdraw.useMutation({ onSuccess: async (data) => { await refresh(); toast.success(data.early ? `Early withdrawal: 5% penalty applied` : "Stake redeemed"); } });
  const createVault = trpc.advanced.vaults.create.useMutation({ onSuccess: refresh }); const deposit = trpc.advanced.vaults.deposit.useMutation({ onSuccess: refresh }); const withdraw = trpc.advanced.vaults.withdraw.useMutation({ onSuccess: refresh }); const schedule = trpc.advanced.vaults.schedule.useMutation({ onSuccess: refresh });
  const setScheduleStatus = trpc.advanced.vaults.setScheduleStatus.useMutation({ onSuccess: refresh });
  const utilsClient = trpc.useUtils();
  async function downloadTaxReport() { const data = await utilsClient.advanced.analytics.taxReport.fetch({ year: new Date().getFullYear(), jurisdiction: "User selected" }); const blob = new Blob([data.csv], { type: "text/csv" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `goldvaults-tax-${new Date().getFullYear()}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  const tabs = [{ id: "staking", label: "Staking", icon: TrendingUp }, { id: "vaults", label: "Savings vaults", icon: PiggyBank }, { id: "recurring", label: "Recurring", icon: Repeat2 }, { id: "analytics", label: "Analytics & tax", icon: Landmark }] as const;
  return <div className="space-y-6"><header><h1 className="text-2xl font-bold">Wealth Hub</h1><p className="text-sm text-muted-foreground">Stake assets, automate savings, and understand portfolio performance.</p></header><div className="flex gap-2 overflow-x-auto" role="tablist">{tabs.map((item) => <button role="tab" aria-selected={tab === item.id} key={item.id} onClick={() => setTab(item.id)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm ${tab === item.id ? "bg-amber-500 text-black" : "bg-white/5"}`}><item.icon className="inline w-4 h-4 mr-1" />{item.label}</button>)}</div>
  {tab === "staking" && <div className="space-y-4"><section className="grid grid-cols-1 sm:grid-cols-4 gap-3 rounded-2xl border border-white/5 bg-card/50 p-4"><input aria-label="Staking asset" value={asset} onChange={(e) => setAsset(e.target.value.toUpperCase())} className="rounded-xl bg-background border border-white/10 p-2"/><input aria-label="Stake amount" type="number" value={amount} onChange={(e) => setAmount(e.target.value)} className="rounded-xl bg-background border border-white/10 p-2"/><select aria-label="Lock period" id="stakeDuration" className="rounded-xl bg-background border border-white/10 p-2"><option value="30">30 days · 4.5% APY</option><option value="90">90 days · 7.5% APY</option><option value="180">180 days · 11% APY</option><option value="365">365 days · 14% APY</option></select><button onClick={() => stake.mutate({ asset, amount, durationDays: Number((document.getElementById("stakeDuration") as HTMLSelectElement).value) as 30 | 90 | 180 | 365, autoCompound: true })} className="rounded-xl bg-amber-500 text-black font-semibold">Stake & auto-compound</button></section><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{stakes.data?.map((item) => <div key={item.id} className="rounded-2xl border border-white/5 bg-card/50 p-4"><div className="flex justify-between"><strong>{item.amount} {item.asset}</strong><span className="text-emerald-400">{item.apy}% APY</span></div><p className="text-xs text-muted-foreground mt-1">Unlocks {new Date(item.unlocksAt).toLocaleDateString()} · {item.autoCompound ? "Auto-compounding" : "Manual payout"}</p>{item.status === "active" && <button onClick={() => unstake.mutate({ id: item.id })} className="mt-3 rounded-lg border border-red-500/20 px-3 py-1.5 text-xs text-red-400">Withdraw {new Date(item.unlocksAt) > new Date() ? "early (5% penalty)" : "stake"}</button>}</div>)}</div></div>}
  {tab === "vaults" && <div className="space-y-4"><section className="flex flex-col sm:flex-row gap-3 rounded-2xl bg-card/50 border border-white/5 p-4"><input aria-label="Vault name" value={vaultName} onChange={(e) => setVaultName(e.target.value)} className="flex-1 rounded-xl bg-background border border-white/10 p-2"/><button onClick={() => createVault.mutate({ name: vaultName, currency: "USDT", targetAmount: "10000" })} className="rounded-xl bg-amber-500 text-black px-4">Create USDT vault</button></section><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{vaults.data?.map((vault) => { const progress = Math.min(100, Number(vault.balance) / Number(vault.targetAmount) * 100); return <div key={vault.id} className="rounded-2xl bg-card/50 border border-white/5 p-4"><div className="flex justify-between"><strong>{vault.name}</strong><span>{progress.toFixed(0)}%</span></div><p className="text-2xl font-bold mt-2">{vault.balance} {vault.currency}</p><div className="h-2 rounded bg-white/10 my-3"><div className="h-2 rounded bg-amber-500" style={{ width: `${progress}%` }}/></div><div className="flex gap-2"><button onClick={() => deposit.mutate({ id: vault.id, amount })} className="rounded-lg bg-emerald-500/20 text-emerald-300 px-3 py-1.5">Add {amount}</button><button onClick={() => withdraw.mutate({ id: vault.id })} className="rounded-lg border border-white/10 px-3 py-1.5">Withdraw</button></div></div>; })}</div></div>}
  {tab === "recurring" && <div className="space-y-4"><section className="rounded-2xl border border-white/5 bg-card/50 p-4 space-y-3"><h2 className="font-semibold">Automate deposits and vault transfers</h2><p className="text-xs text-muted-foreground">Vault transfers use your wallet balance. External recurring deposits require a tokenized saved payment method from the configured payment processor.</p><div className="flex flex-col sm:flex-row gap-2"><button disabled={!vaults.data?.[0]} onClick={() => vaults.data?.[0] && schedule.mutate({ kind: "vault_transfer", vaultId: vaults.data[0].id, currency: vaults.data[0].currency, amount, frequency: "weekly" })} className="rounded-xl bg-amber-500 text-black px-4 py-2 disabled:opacity-50">Schedule {amount} weekly to vault</button><input aria-label="Saved payment method token" value={paymentMethodToken} onChange={(event)=>setPaymentMethodToken(event.target.value)} placeholder="Saved payment method token" className="flex-1 rounded-xl bg-background border border-white/10 px-3"/><button disabled={!paymentMethodToken} onClick={()=>schedule.mutate({kind:"deposit",currency:asset,amount,frequency:"monthly",paymentMethodToken})} className="rounded-xl bg-emerald-500/20 text-emerald-300 px-4 py-2 disabled:opacity-50">Schedule monthly deposit</button></div></section>{schedules.data?.map((item) => <div key={item.id} className="rounded-xl bg-white/5 p-3 flex flex-col sm:flex-row sm:items-center justify-between gap-2"><span>{item.kind.replace("_"," ")} · {item.amount} {item.currency} · {item.frequency}</span><div className="flex items-center gap-2"><span>{item.status} · next {new Date(item.nextRunAt).toLocaleDateString()}</span>{item.status!=="cancelled"&&<><button onClick={()=>setScheduleStatus.mutate({id:item.id,status:item.status==="paused"?"active":"paused"})} className="text-amber-400">{item.status==="paused"?"Resume":"Pause"}</button><button onClick={()=>setScheduleStatus.mutate({id:item.id,status:"cancelled"})} className="text-red-400">Cancel</button></>}</div></div>)}</div>}
  {tab === "analytics" && <div className="space-y-4"><div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[{ label: "Volume", value: analytics.data?.volume ?? 0 }, { label: "Realized gain/loss", value: analytics.data?.realizedGains ?? 0 }, { label: "Sharpe ratio", value: analytics.data?.sharpeRatio ?? 0 }, { label: "Max drawdown", value: `${(analytics.data?.maxDrawdown ?? 0).toFixed(2)}%` }, { label: "Loyalty tier", value: loyalty.data?.tier ?? "bronze" }].map((metric) => <div key={metric.label} className="rounded-2xl bg-card/50 border border-white/5 p-4"><p className="text-xs text-muted-foreground">{metric.label}</p><p className="text-lg font-bold capitalize">{typeof metric.value === "number" ? metric.value.toFixed(2) : metric.value}</p></div>)}</div><section className="rounded-2xl bg-card/50 border border-white/5 p-4"><h2 className="font-semibold">Allocation and drift</h2>{analytics.data?.allocation.map((item) => {const drift=analytics.data?.allocationDrift.find((row)=>row.asset===item.asset);return <div key={item.asset} className="flex justify-between py-2 border-b border-white/5"><span>{item.asset}</span><span>{item.amount.toLocaleString()} <small className={(drift?.driftPercent??0)>0?"text-amber-400":"text-blue-400"}>{drift?`${drift.driftPercent>=0?"+":""}${drift.driftPercent.toFixed(1)}% drift`:""}</small></span></div>})}<button onClick={downloadTaxReport} className="mt-4 rounded-xl bg-amber-500 text-black px-4 py-2"><Download className="inline w-4 h-4 mr-1"/>Download FIFO tax CSV</button></section></div>}
  </div>;
}
