import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { CreditCard, FileText, LifeBuoy, Scale, ShieldAlert, Webhook } from "lucide-react";

export default function AdminOperations() {
  const [tab,setTab]=useState<"aml"|"disputes"|"tickets"|"webhooks"|"blog"|"programs">("aml"); const utils=trpc.useUtils();
  const [webhookName,setWebhookName]=useState("Accounting"); const [webhookUrl,setWebhookUrl]=useState("");
  const [postTitle,setPostTitle]=useState(""); const [postSlug,setPostSlug]=useState(""); const [postExcerpt,setPostExcerpt]=useState(""); const [postContent,setPostContent]=useState("");
  const aml=trpc.advanced.admin.aml.list.useQuery({},{enabled:tab==="aml"}); const disputes=trpc.advanced.admin.p2pDisputes.list.useQuery(undefined,{enabled:tab==="disputes"}); const tickets=trpc.advanced.admin.tickets.list.useQuery(undefined,{enabled:tab==="tickets"}); const hooks=trpc.advanced.admin.webhooks.list.useQuery(undefined,{enabled:tab==="webhooks"}); const posts=trpc.advanced.admin.blog.list.useQuery(undefined,{enabled:tab==="blog"}); const affiliates=trpc.advanced.admin.affiliates.list.useQuery(undefined,{enabled:tab==="programs"}); const payouts=trpc.advanced.admin.affiliates.payouts.useQuery(undefined,{enabled:tab==="programs"}); const pendingCards=trpc.advanced.admin.cards.pending.useQuery(undefined,{enabled:tab==="programs"});
  const sar=trpc.advanced.admin.aml.fileSar.useMutation({onSuccess:()=>utils.advanced.admin.aml.list.invalidate()}); const resolve=trpc.advanced.admin.p2pDisputes.resolve.useMutation({onSuccess:()=>utils.advanced.admin.p2pDisputes.list.invalidate()}); const reply=trpc.advanced.admin.tickets.reply.useMutation({onSuccess:()=>utils.advanced.admin.tickets.list.invalidate()}); const createHook=trpc.advanced.admin.webhooks.create.useMutation({onSuccess:(data)=>{utils.advanced.admin.webhooks.list.invalidate();toast.success(`Webhook created. Secret: ${data.secret}`)}}); const upsert=trpc.advanced.admin.blog.upsert.useMutation({onSuccess:()=>utils.advanced.admin.blog.list.invalidate()}); const setAffiliateStatus=trpc.advanced.admin.affiliates.setStatus.useMutation({onSuccess:()=>utils.advanced.admin.affiliates.list.invalidate()}); const approvePayout=trpc.advanced.admin.affiliates.approvePayout.useMutation({onSuccess:()=>utils.advanced.admin.affiliates.payouts.invalidate()}); const decideCard=trpc.advanced.admin.cards.decide.useMutation({onSuccess:()=>utils.advanced.admin.cards.pending.invalidate()});
  const tabs=[{id:"aml",label:"AML & SAR",icon:ShieldAlert},{id:"disputes",label:"P2P disputes",icon:Scale},{id:"tickets",label:"Support",icon:LifeBuoy},{id:"webhooks",label:"Webhooks",icon:Webhook},{id:"blog",label:"Blog CMS",icon:FileText},{id:"programs",label:"Cards & affiliates",icon:CreditCard}] as const;
  return <div className="space-y-6"><header><h1 className="text-2xl font-bold">Compliance & Operations</h1><p className="text-sm text-muted-foreground">Resolve monitored workflows and manage external content.</p></header><div className="flex overflow-x-auto gap-2">{tabs.map((item)=><button key={item.id} onClick={()=>setTab(item.id)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-sm ${tab===item.id?"bg-amber-500 text-black":"bg-white/5"}`}><item.icon className="inline w-4 h-4 mr-1"/>{item.label}</button>)}</div>
  {tab==="aml"&&<Panel title="Transaction monitoring">{aml.data?.map((item)=><Row key={item.id} title={`${item.rule} · Risk ${item.riskScore}`} subtitle={`User #${item.userId} · ${item.status}`}><button onClick={()=>sar.mutate({alertId:item.id,jurisdiction:"US",narrative:`Automated monitoring detected ${item.rule}. Compliance reviewed the associated user and transaction activity and determined that a suspicious activity report is required.`})} className="text-red-400">File SAR</button></Row>)}</Panel>}
  {tab==="disputes"&&<Panel title="Escrow disputes">{disputes.data?.map((item)=><Row key={item.id} title={`Order #${item.orderId}`} subtitle={item.reason}><div className="flex gap-2"><button onClick={()=>resolve.mutate({disputeId:item.id,decision:"buyer",resolution:"Evidence supports releasing escrow to the buyer."})} className="text-emerald-400">Buyer</button><button onClick={()=>resolve.mutate({disputeId:item.id,decision:"seller",resolution:"Evidence supports refunding escrow to the seller."})} className="text-amber-400">Seller</button></div></Row>)}</Panel>}
  {tab==="tickets"&&<Panel title="Support queue">{tickets.data?.map((item)=><Row key={item.id} title={`#${item.id} · ${item.subject}`} subtitle={`${item.priority} · ${item.status}`}><button onClick={()=>reply.mutate({ticketId:item.id,message:"Your ticket has been reviewed by GoldVaults Support. Please reply if further assistance is required.",status:"waiting_user"})} className="text-blue-400">Reply</button></Row>)}</Panel>}
  {tab==="webhooks"&&<Panel title="Integration webhooks"><div className="grid grid-cols-1 md:grid-cols-[1fr_2fr_auto] gap-2 mb-4"><input aria-label="Webhook name" value={webhookName} onChange={(e)=>setWebhookName(e.target.value)} placeholder="Endpoint name" className="rounded-xl bg-gray-950 border border-gray-700 p-2"/><input aria-label="HTTPS webhook URL" value={webhookUrl} onChange={(e)=>setWebhookUrl(e.target.value)} placeholder="https://crm.example.com/events" className="rounded-xl bg-gray-950 border border-gray-700 p-2"/><button disabled={!webhookUrl.startsWith("https://")} onClick={()=>createHook.mutate({name:webhookName,url:webhookUrl,events:["deposit.confirmed","kyc.approved","withdrawal.large"]})} className="rounded-xl bg-amber-500 text-black px-4 py-2 disabled:opacity-50">Create endpoint</button></div>{hooks.data?.map((item)=><Row key={item.id} title={item.name} subtitle={`${item.url} · ${item.events.join(", ")}`}/>)}</Panel>}
  {tab==="blog"&&<Panel title="Knowledge base CMS"><div className="grid grid-cols-1 md:grid-cols-2 gap-2 mb-4"><input aria-label="Article title" value={postTitle} onChange={(e)=>{setPostTitle(e.target.value);setPostSlug(e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""))}} placeholder="Article title" className="rounded-xl bg-gray-950 border border-gray-700 p-2"/><input aria-label="SEO-friendly slug" value={postSlug} onChange={(e)=>setPostSlug(e.target.value)} placeholder="seo-friendly-slug" className="rounded-xl bg-gray-950 border border-gray-700 p-2"/><textarea aria-label="Article excerpt" value={postExcerpt} onChange={(e)=>setPostExcerpt(e.target.value)} placeholder="Search and social excerpt" className="md:col-span-2 rounded-xl bg-gray-950 border border-gray-700 p-2"/><textarea aria-label="Article content" value={postContent} onChange={(e)=>setPostContent(e.target.value)} rows={7} placeholder="Educational article content" className="md:col-span-2 rounded-xl bg-gray-950 border border-gray-700 p-2"/><div className="md:col-span-2 flex gap-2"><button disabled={postTitle.length<3||postExcerpt.length<10||postContent.length<20} onClick={()=>upsert.mutate({title:postTitle,slug:postSlug,excerpt:postExcerpt,content:postContent,seoTitle:postTitle,seoDescription:postExcerpt.slice(0,320),status:"draft"})} className="rounded-xl border border-amber-500/30 text-amber-400 px-4 py-2 disabled:opacity-50">Save draft</button><button disabled={postTitle.length<3||postExcerpt.length<10||postContent.length<20} onClick={()=>upsert.mutate({title:postTitle,slug:postSlug,excerpt:postExcerpt,content:postContent,seoTitle:postTitle,seoDescription:postExcerpt.slice(0,320),status:"published"})} className="rounded-xl bg-amber-500 text-black px-4 py-2 disabled:opacity-50">Publish</button></div></div>{posts.data?.map((item)=><Row key={item.id} title={item.title} subtitle={`${item.status} · /blog/${item.slug}`}/>)}</Panel>}
  {tab==="programs"&&<div className="grid grid-cols-1 xl:grid-cols-3 gap-4"><Panel title="Physical card requests">{pendingCards.data?.map((card)=><Row key={card.id} title={`Card #${card.id} · User #${card.userId}`} subtitle={`${card.cardholderName} · ${card.cardType}`}><div className="flex gap-2"><button onClick={()=>decideCard.mutate({id:card.id,status:"issued"})} className="text-emerald-400">Issue</button><button onClick={()=>decideCard.mutate({id:card.id,status:"rejected"})} className="text-red-400">Reject</button></div></Row>)}</Panel><Panel title="Affiliate applications">{affiliates.data?.map((profile)=><Row key={profile.id} title={`Affiliate #${profile.id} · User #${profile.userId}`} subtitle={`${profile.status} · ${profile.commissionRate}% commission · $${profile.totalEarned} earned`}><div className="flex gap-2"><button onClick={()=>setAffiliateStatus.mutate({id:profile.id,status:"approved"})} className="text-emerald-400">Approve</button><button onClick={()=>setAffiliateStatus.mutate({id:profile.id,status:"suspended"})} className="text-red-400">Suspend</button></div></Row>)}</Panel><Panel title="Affiliate payouts">{payouts.data?.map((payout)=><Row key={payout.id} title={`${payout.amount} ${payout.currency}`} subtitle={`Affiliate #${payout.affiliateId} · ${payout.status}`}><button onClick={()=>approvePayout.mutate({id:payout.id})} className="text-emerald-400">Approve payout</button></Row>)}</Panel></div>}
  </div>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/5 bg-card/50 p-5"><h2 className="font-semibold mb-4">{title}</h2><div className="space-y-2">{children}</div></section>}
function Row({title,subtitle,children}:{title:string;subtitle:string;children?:React.ReactNode}){return <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 rounded-xl bg-white/5 p-3"><div><strong className="text-sm">{title}</strong><p className="text-xs text-muted-foreground max-w-2xl">{subtitle}</p></div>{children}</div>}
